version: '3.8'

services:
  ia-ts-app:
    image: ia-ts-app:latest
    networks:
      - network_swarm_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_swarm_public"
        - "traefik.http.routers.ia-ts-app.rule=Host(`api-transcricao.mlgrupo.com.br`)"
        - "traefik.http.routers.ia-ts-app.entrypoints=websecure"
        - "traefik.http.routers.ia-ts-app.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.ia-ts-app.loadbalancer.server.port=9898"
    environment:
      - NODE_ENV=production
      - PORT=9898
      - TZ=America/Sao_Paulo

      # Banco externo
      - DB_HOST=178.156.151.200
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=orPHoLdFAsHObWEstaCyCHarI
      - DB_NAME=GrupoML_prod

      # Google OAuth
      - GOOGLE_CLIENT_ID=1020668841888-m44ns0c4fatagdh47st2ccsj4seaf5o5.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - REDIRECT_URI=http://localhost:5173/callback
      # API
      - API_KEY=93e7b8b2-4fc7-4c67-9b27-ccf92fe401d3
      - WEBHOOK_URL=https://whk.supercaso.com.br/webhook/33443dbe-b7c2-43c9-901f-aa6b01d503ad

    volumes:
      - /opt/ia-ts-app/temp:/app/temp:rw

networks:
  network_swarm_public:
    external: true
