version: '3.8'

services:
  ia-ts-app:
    image: ia-ts-app:latest
    networks:
      - network_swarm_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_swarm_public"
        - "traefik.http.routers.ia-ts-app.rule=Host(`api-transcricao.mlgrupo.com.br`)"
        - "traefik.http.routers.ia-ts-app.entrypoints=websecure"
        - "traefik.http.routers.ia-ts-app.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.ia-ts-app.loadbalancer.server.port=9898"
    environment:
      - NODE_ENV=production
      - PORT=9898
      - TZ=America/Sao_Paulo

      # Banco externo
      - DB_HOST=178.156.151.200
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=orPHoLdFAsHObWEstaCyCHarI
      - DB_NAME=GrupoML_prod

      # Google OAuth
      - GOOGLE_CLIENT_ID=1020668841888-m44ns0c4fatagdh47st2ccsj4seaf5o5.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - REDIRECT_URI=https://auth.mlgrupo.com.br/callback
      # API
      - X_API_KEY=6e0c6c5c-31f3-4bf4-aabc-71a1d6fb7f7a
      - WEBHOOK_URL=https://whk.supercaso.com.br/webhook/status-transcricao
      - FOLDER_NAME_GRAVACAO='Gravação'
      - FOLDER_NAME_TRANSCRICAO='Transcricão'
      - ROOT_FOLDER_NAME='Meet Recordings'

    volumes:
      - /opt/ia-ts-app/temp:/app/temp:rw

networks:
  network_swarm_public:
    external: true
