version: '3.8'

services:
  backend:
    container_name: backend_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9898:9898" # Altere para a porta que seu backend expõe
    restart: always
    depends_on: []
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 32G