version: '3.8'

services:
  backend:
    container_name: backend_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9898:9898"
    restart: always
    volumes:
      - ./temp:/app/temp
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 32G
        reservations:
          cpus: '4'
          memory: 16G
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/python
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9898/health"]
      interval: 30s
      timeout: 10s
      retries: 3