#este arquivo é para subir um banco postgres para o ambiente de desenvolvimento
services:
  postgres:
    container_name: ambiente_dev
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db-ia
    ports:
      - "5432:5432"
