version: '3.8'

services:
  backend:
    container_name: backend_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./temp:/app/temp
      - ./python/models:/app/python/models
      - ./python/outputs:/app/python/outputs
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 32G
        reservations:
          cpus: '4'
          memory: 16G
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/python
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3